### ISSUE TITLE
Ubuntu GKSU no longer supported

### ISSUE THREAD

**Issue by ZaranTheWise** [leolewis/openvisualtraceroute#2]
open visual trace route requires the gksu dependency in Ubuntu. GKSU is no longer supported or available. Is there a work around/fix?

**Comment by sschyu** [comment]
+1
Ubuntu 18.04 LTS no gksu package.

**Comment by pbhj** [comment]
+1
I think you can fix it with equivs to spoof the gksu package being installed and then use some scripting of pkexec to mimic gksu ... but it would be nice to update the app so that wasn't necessary.

FWIW I used `equivs` packages to make a fake gksu that I installed with `dpkg -i`; then `ovtr` installed without complaints. However, running /usr/share/OpenVisualTraceRoute/ovtr.sh (or the same with `sudo`) appears to work but never manages to do any route tracing (output pasted to https://pastebin.com/ALUKw4Mq). I can do traceroute with mtr or tracert as an ordinary user, I guess I'd probably prefer just to be able to use either of those and then parse the output to make a map (I should check out maxmind and GMaps/OSM ...).

I tried using `pkexec` but couldn't muster a working incantation (I tried `xhost +local:`) and just get `xhost:  unable to open display ""`.

**Comment by leolewis** [comment]
Version 2.0.0 no longer requires root/sudo to execute a traceroute.
